apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: microservices-demo
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.GIT_COMMIT}}"
  artifacts:
    - image: emailservice
      context: src/emailservice
    - image: productcatalogservice
      context: src/productcatalogservice
    - image: recommendationservice
      context: src/recommendationservice
    - image: shoppingassistantservice
      context: src/shoppingassistantservice
    - image: shippingservice
      context: src/shippingservice
    - image: checkoutservice
      context: src/checkoutservice
    - image: paymentservice
      context: src/paymentservice
    - image: currencyservice
      context: src/currencyservice
    - image: cartservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: src/frontend
    - image: adservice
      context: src/adservice
  local:
    push: true
    useDockerCLI: true
    useBuildkit: true
